CREATE DATABASE IF NOT EXISTS $METABASE_DB_NAME;
CREATE USER IF NOT EXISTS '$METABASE_DB_USERNAME'@'%' IDENTIFIED BY '$METABASE_DB_PASSWORD';
GRANT ALL PRIVILEGES ON $METABASE_DB_NAME.* TO '$METABASE_DB_USERNAME'@'%';
